# To specify the args required for the build because at the time of writing
# docker-compose didn't support build secrets

# How to use this file
# If you don't want to be bugged for input then fill out the relevant fields
# Then the docker build py command will read them from here

# Make sure the passwords saved in the relevant files in the secrets
# section exist, and are greater than 6 chars if you don't want to be
# prompted to enter a new one

[build-args]
D_USER = 'default'
DOTFILE_GIT_REPO = 'https://github.com/Sierra-Alpha/dot
files.git'
SSH_EMAIL = 'default@example.com'

# Not the actual secrets but the path to the file that contains them
[secrets]
root_password = 'root_password.txt'
vnc_password = 'vnc_password.txt'
user_password = 'user_password.txt'

# Language for prompts of missing values (currently only english implemented)
[language]
english.D_USER = 'user name'
english.DOTFILE_GIT_REPO = 'dotfile git repository address'
english.SSH_EMAIL = 'email address to use for ssh key-gen'
english.root_password = 'root password'
english.vnc_password = 'vnc password'
english.user_password = 'user password'
