#!/bin/bash -x

export X11VNC_CREATE_GEOM=1920x1080x24
vncserver \
    -verbose \
    -localhost no --I-KNOW-THIS-IS-INSECURE \
    -cleanstale \
    -fg \
    -xstartup /home/shaun/.xinitrc \
    -SecurityTypes None \
    :0
