#!/bin/bash -x

#     matapihi the window that looks into and Xserver through SSH tunels and VNC
#     Copyright (C) 2020 Shaun Alexander

#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.

#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.

#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.

service ssh restart

# If the password is expired we need to wait for user to reset
# it when connecting to SSH (not great that we're polling it,
# but couldn't figure a way to be woken for it)
while chage -l "$D_USER" | grep "password must be changed"
do
    sleep 5
done

# Now that we are logged in make the Xvncserver do a loop, which means we can
# relaunch the VNC viewer connection without needing to restart the container
# It's in the fg to keep the docker container alive.
su - $D_USER<<EOF
while true
do
    vncserver \
        -verbose \
        -useold \
        -cleanstale \
        -localhost yes \
        -xdisplaydefaults \
        -fg \
        :0
    sleep 1
done
EOF
