#! /bin/bash

# Launch xterm with my favourite colour scheme and ask user for start up scripts
# if they dont exist then run them and exit to bash if anything goes wrong or
# user exits program, instead of closing client.
xrdb -merge ~/.Xresources
xterm -ls -maximize -e \
      "PATH=$PATH:~/.matapihi; matapihi -r"

