#! /bin/bash

m_exit=~/.matapihi/matapihi_exit
m_init=~/.matapihi/matapihi_init
m_log=~/.matapihi/matapihi.log
m_start=~/.matapihi/matapihi_start


log () {
    if [ "$#" -ne 0 ]; then
        printf '%s\n' "$@"
    else
        cat
    fi | ts '[%Y-%m-%d %H:%M:%S]' >> "$m_log"
}


get_scripts () {
    local in_out output script_url
    in_out="$1"
    output="$2"

    log "Prompting user for $output script"
    echo "If your seeing this it's either the first time you've connected to Matapihi"
    echo "or your $output script has failed, you can try to set up a new script."
    echo "A blank entry will set the script to setup the default scripts"
    echo "The following will ovewrite any $output script"
    echo "(Enter q here to quit before changes are made)"
    read quit

    # If input is q
    if [[ "$quit" == "q" ]]
    then
        log "User exited from $output prompt without providing a script"
	      echo "Run '. $m_init' when your ready to restart"
        exit 1
    fi

    echo "Enter the script url (for wget) you want to run when $in_out Matapihi: "
    read script_url

    # If input is blank
    if test -z "$script_url"
    then
        echo "Writing base bash script" | tee >(log)
        printf "#! /bin/bash\n\necho in $output\n" > "$output"
        if [[ "$output" == "$m_start" ]]
        then
            printf "\necho starting bash prompt\nbash -i\n" >> "$output"
        fi
    else
	      echo "Writing custom script $script_url" | tee >(log)
        wget -O "$output" -- "$script_url" \
            && echo "Download complete" | tee >(log)
    fi

    echo "You should check the script is as you expect before you run it,"
    echo "File will now open in a new window, Press enter once review is complete"
    echo "Then d to delete the file or any other key to continue"
    read

    less -X -n -i -F "$output"
    echo "Are you happy for this script to execute? (d to destroy it, anything else to continue)"
    read destroy
    if [[ "$destroy" == "d" ]]
    then
        log "Script rejected - removing"
        rm "$output" && echo "$output removed"
    else
        log "Set permissions to execute for $output"
        chmod +x "$output"
    fi
}


check_files () {
    if [[ ! -f "$m_start" ]]
    then
        get_scripts "an initial client connects to" "$m_start"
    fi

    if [[ ! -f "$m_exit" ]]
    then
        get_scripts "shutting eveything down before the final client disconnects from" "$m_exit"
        echo "You may like to call $m_exit to test the disconnect script,"
        echo "Note: doing so shouldn't kill the session"
    fi
}

while [[ ! -f "${m_start}" || ! -f "${m_exit}" ]]; do
    echo checking files | tee >(log)
    check_files
done
