#! /bin/bash

help () {
    echo "\
Usage: matapihi [option]

only one option is supported at a time

NOTE: It works best if supplied scripts for \`matapihi_start\`
and \`matapihi_exit\` are idempotent, that is they can be executed
multiple times with the same outcome.

Options:

   -c   clear
           Clears the previously loaded \`matapihi_start\` and
           \`matapihi_exit\` scripts

   -h   help
           Launches this help and exits

   -i   initialise
           If the scripts \`matapihi_start\` or \`matapihi_exit\`
           don't exist it prompts the user for an url to wget them

   -q   quit
           Run the user defined \`matapihi_exit\` script, this should
           shut down everything and kill the session

   -r   refresh/run
           If the scripts don't exist call init then;
           This will re-run the scripts in the order of \`matapihi_exit\`
           then \`matapihi -s\` and when start closes \`matapihi -q\`

   -s   start
           This will run the \`matapihi_start\` script

"
}


# if weve had no parms or too many then set to help
if [ "$#" -ne 1 ]
then
    set -- "-h"
fi


m_exit=~/.matapihi/matapihi_exit
m_init=~/.matapihi/matapihi_init
m_log=~/.matapihi/matapihi.log
m_start=~/.matapihi/matapihi_start
m_run=~/.matapihi/matapihi


log () {
    if [ "$#" -ne 0 ]; then
        printf '%s\n' "$@"
    else
        cat
    fi | ts '[%Y-%m-%d %H:%M:%S]' >> "$m_log"
}


log "Matapihi started with option $1"

case "$1" in
    -c)
        log "In clear, removing $m_start & $m_exit"
        rm "$m_start" "$m_exit" 2>&1 | tee >(log)
        ;;
    -h)
        log "Displaying help"
        help
        exit 0
        ;;
    -i)
        log "Starting init"
        . "$m_init"
        ;;
    -q)
        log "Prompt to leave matapihi"
        echo "Exiting Matapihi do you want to cancel?"
        echo "Blank to continue exiting, any other key to cancel"
        read leavex

        # If input is blank
        if test -z "$leavex"
        then
            log "leaving matapihi"
            echo "Calling $m_exit"
            . "$m_exit"
            exit 0
        fi

        log "User doesn't want to exit, leaving them at a bash prompt"
        exec /bin/bash -i
        ;;
    -r)
        . "$m_init"
        echo init complete, running $m_exit to refresh environment | tee >(log)
        . "$m_exit"
        . "$m_run" -s
        . "$m_run" -q
        echo "Matapihi failed" | tee >(log)
        ;;
    -s)
        echo "Running start script"
        . "$m_start" \
            || (echo "Start script failed, try editing '$m_start'" | tee >(log) \
                && echo "or removing it and retrying by calling 'matapihi -i'" | tee >(log))
        ;;
esac
